name: build
on:
  push:
  pull_request:
jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.0'
      - run: go version
      - run: go build ./...
      - run: go test -race ./...
